#!/bin/sh
# Runs INSIDE the bench container (privileged). Two network namespaces joined by
# a veth pair, one tincd in each, iperf3 across the tunnel at a fixed offered
# rate. Prints one CSV line per arm on stdout; everything else goes to stderr.
#
# What is measured, and why this way:
#   * CPU is read from /proc/<pid>/stat (utime+stime, clock ticks) bracketing the
#     transfer, not from `docker stats` -- a sampler cannot see a 30 s window
#     accurately and mixes in the harness's own work.
#   * Memory is VmHWM (peak resident) from /proc/<pid>/status, because the
#     question "how much RAM does this need on a router" is about the peak, not
#     about whatever RSS happens to be at the end.
#   * Both daemons run at -d0. Logging is not free and the arms must not differ
#     in how much of it they do.
#   * Every run is CALIBRATED against a fixed busy loop measured in the same
#     container, immediately before and after the transfer. This is not
#     decoration: on an intel_pstate/powersave host the identical transfer --
#     same arm, same 0.433 Mpkt, same 100 Mbit/s -- cost anywhere between 7 %
#     and 26 % of a core, because a boosted core does the same work in a third
#     of the CPU-seconds. CPU time is not a unit of work on such a machine.
#     cpu_norm = cpu_seconds / calibration_seconds is, and it is what the arms
#     are compared on.
#   * The offered rate is fixed (iperf3 -b) so the arms do equal work; the
#     achieved rate is reported too, and if an arm cannot keep up, that is the
#     finding rather than a reason to compare CPU at different throughputs.
#   * The default load is UDP with a fixed datagram size, because the question
#     is CPU per packet and TCP does not hold the packet count still: the tun
#     device coalesces segments, so the daemon can see half as many, twice as
#     large reads on one run as on the next. Measured that way the same arm
#     came out at 23.7 %, 10.6 % and 23.9 % of a core -- a spread wider than
#     the difference being looked for. MODE=tcp runs the TCP load instead, and
#     the packet counters below are printed either way, so a result can always
#     be checked against the work actually done.
set -eu

ARM=$1          # baseline | baseline-o3 | plain | sf | obfs | quic | https
SECONDS_RUN=${SECONDS_RUN:-30}
RATE=${RATE:-100M}
PORT=655
A_IP=10.99.0.1
B_IP=10.99.0.2
A_VPN=10.180.0.1
B_VPN=10.180.0.2
RUN=/run/bench
NODES=$RUN/nodes

CORE_TINCD=/usr/local/sbin/tincd
CORE_TINC=/usr/local/sbin/tinc
BASE_TINCD=/opt/baseline/sbin/tincd
BASE_O3_TINCD=/opt/baseline-o3/sbin/tincd

case "$ARM" in
	baseline)    TINCD=$BASE_TINCD ;;
	baseline-o3) TINCD=$BASE_O3_TINCD ;;
	*)           TINCD=$CORE_TINCD ;;
esac

log() { echo "[$ARM] $*" >&2; }

cleanup() {
	# KEEP_LOGS=<dir> saves the two daemon logs before teardown: a run whose
	# carrier column says something other than the arm asked for can then be
	# explained instead of only noticed.
	if [ -n "${KEEP_LOGS:-}" ]; then
		mkdir -p "$KEEP_LOGS"
		for n in a b; do
			[ -f "$RUN/$n.log" ] && cp "$RUN/$n.log" "$KEEP_LOGS/$ARM-$n.log"
		done
	fi
	for n in a b; do
		[ -f "$RUN/$n.pid" ] && kill -TERM "$(awk '{print $1}' "$RUN/$n.pid")" 2>/dev/null || true
	done
	pkill -f 'iperf3 -s' 2>/dev/null || true
	sleep 1
	ip netns del a 2>/dev/null || true
	ip netns del b 2>/dev/null || true
	rm -rf "$RUN"
}
trap cleanup EXIT
cleanup
mkdir -p "$NODES/a/hosts" "$NODES/b/hosts"

# ------------------------------------------------------------------ topology
ip netns add a
ip netns add b
ip link add va type veth peer name vb
ip link set va netns a
ip link set vb netns b
ip netns exec a ip addr add "$A_IP/24" dev va
ip netns exec b ip addr add "$B_IP/24" dev vb
ip netns exec a ip link set va up
ip netns exec b ip link set vb up
ip netns exec a ip link set lo up
ip netns exec b ip link set lo up

# -------------------------------------------------------------------- config
# Classic tinc.conf, byte-for-byte the same for both daemons except the extra
# transport lines, which upstream simply does not have. Keys are generated by
# the core CLI in classic mode; the on-disk format is identical for both.
write_node() {
	name=$1 vpn=$2 addr=$3 extra=$4
	d=$NODES/$name
	{
		echo "Name = $name"
		echo "Mode = router"
		echo "Port = $PORT"
		echo "AddressFamily = ipv4"
		echo "PingInterval = 10"
		echo "PingTimeout = 5"
		# One dialler, one acceptor. With AutoConnect left at its default both
		# nodes dial each other, both carrier dials succeed, and the connection
		# that survives the id_h dedup reports `plain' in dump connections -- so
		# an arm would silently measure the plain data path while claiming to
		# measure its own carrier. The carrier tests use the same rendezvous
		# shape for the same reason.
		echo "AutoConnect = no"
		[ -n "$extra" ] && printf '%s\n' "$extra"
	} > "$d/tinc.conf"
	{
		printf 'Subnet = %s/32\n' "$vpn"
		printf 'Address = %s\nPort = %s\n' "$addr" "$PORT"
		# The peer's accept mask. Without it a cold dialler knows nothing about
		# what the other end accepts, assumes `plain', and every arm silently
		# measures the plain path: "Carrier candidates for b: plain (peer
		# accepts plain)". In the field this arrives over ANS_PUBKEY/ACK, but
		# that is after the first connection is already up.
		printf 'Transports = plain,sf,obfs,https,quic\n'
	} > "$d/hosts/$name"
	# shellcheck disable=SC2016  # $INTERFACE is expanded by tincd, not here
	printf '#!/bin/sh\nip link set "$INTERFACE" up\nip addr add %s/24 dev "$INTERFACE"\n' "$vpn" > "$d/tinc-up"
	chmod +x "$d/tinc-up"
	"$CORE_TINC" -c "$d" generate-keys >/dev/null 2>&1
}

case "$ARM" in
	baseline|baseline-o3) EXTRA="" ;;
	plain)    EXTRA="PreferredTransports = plain" ;;
	sf)       EXTRA="PreferredTransports = sf
SingleFlow = yes" ;;
	obfs)     EXTRA="PreferredTransports = obfs" ;;
	quic)     EXTRA="PreferredTransports = quic" ;;
	https)    EXTRA="PreferredTransports = https" ;;
	*) echo "unknown arm $ARM" >&2; exit 2 ;;
esac

write_node a "$A_VPN" "$A_IP" "$EXTRA"
write_node b "$B_VPN" "$B_IP" "$EXTRA"
echo "ConnectTo = b" >> "$NODES/a/tinc.conf"
cp "$NODES/a/hosts/a" "$NODES/b/hosts/a"
cp "$NODES/b/hosts/b" "$NODES/a/hosts/b"

# --------------------------------------------------------------------- start
for n in a b; do
	# -d0 for measurement: logging is not free. DEBUG_LEVEL raises it for
	# diagnosis only -- never for a row that ends up in a result table.
	ip netns exec "$n" "$TINCD" -D -d"${DEBUG_LEVEL:-0}" -c "$NODES/$n" --pidfile "$RUN/$n.pid" \
		>> "$RUN/$n.log" 2>&1 &
done

# Wait for the data path this arm is supposed to measure.
#
# The https carrier is deliberately not a UDP path: become_established() marks
# the link TCPONLY|INDIRECT so that one TLS flow carries meta and data, which is
# the whole point (bare UDP next to a connection pretending to be HTTPS would
# give the cover away). So https is ready when the tunnel passes a ping; every
# other arm must reach "directly with UDP", because for them anything else
# would mean the measurement had quietly moved to the meta channel.
case "$ARM" in
	https) WANT=meta ;;
	*)     WANT=udp ;;
esac

t0=$(date +%s)
while :; do
	r=$("$CORE_TINC" -c "$NODES/a" --pidfile "$RUN/a.pid" info b 2>/dev/null \
		| awk -F': *' '/^Reachability:/{print $2}')

	if [ "$WANT" = meta ]; then
		ip netns exec a ping -c1 -W1 "$B_VPN" >/dev/null 2>&1 && break
	fi

	[ "$WANT" = udp ] && [ "$r" = "directly with UDP" ] && break
	if [ $(( $(date +%s) - t0 )) -gt "${UP_TIMEOUT:-90}" ]; then
		log "tunnel never came up (last: ${r:-none})"
		"$CORE_TINC" -c "$NODES/a" --pidfile "$RUN/a.pid" info b 2>&1 | sed 's/^/[info] /' >&2
		"$CORE_TINC" -c "$NODES/a" --pidfile "$RUN/a.pid" dump nodes 2>&1 | sed 's/^/[nodes] /' >&2
		exit 1
	fi
	sleep 1
done
log "tunnel up after $(( $(date +%s) - t0 ))s (path: ${r:-unknown})"
path=$(printf '%s' "${r:-unknown}" | tr ' ' '-')

# The tun device, found by the address tinc-up put on it.
tun_dev() { ip netns exec "$1" ip -o -4 addr show | awk -v ip="$2" '$0 ~ ip {print $2; exit}'; }
# Only A's counter is read: the two ends see the same packets, and one counter
# that is certainly the sender's is a better unit than a sum that hides a loss.
TUN_A=$(tun_dev a "$A_VPN")

pmtu=$("$CORE_TINC" -c "$NODES/a" --pidfile "$RUN/a.pid" dump nodes 2>/dev/null \
	| awk '/^b /{for(i=1;i<=NF;i++) if($i=="pmtu") print $(i+1)}')

# The carrier actually negotiated, recorded per run. Without it a silent
# fallback -- a carrier that could not be dialled, or a datagram that did not
# fit a carrier's ceiling -- would be measured as if it were the arm asked for,
# and the row would quietly be a duplicate of the plain one.
carrier=$("$CORE_TINC" -c "$NODES/a" --pidfile "$RUN/a.pid" dump connections 2>/dev/null \
	| awk '/^b /{for(i=1;i<=NF;i++) if($i=="transport") print $(i+1)}' | head -1)
[ -n "$carrier" ] || carrier=unknown
log "carrier in use: $carrier (pmtu ${pmtu:-?})"

# -------------------------------------------------------------------- sample
# tinc's pidfile is not just a pid: it is "<pid> <key> <address> <port>".
pid_of() { awk '{print $1}' "$RUN/$1.pid"; }
cpu_ticks() { awk '{print $14+$15}' "/proc/$(pid_of "$1")/stat"; }
hwm_kb() { awk '/VmHWM/{print $2}' "/proc/$(pid_of "$1")/status"; }
# Packets crossing the tunnel device: the unit the daemon's per-packet work is
# actually proportional to. Without this a CPU number cannot be checked.
# A fixed amount of pure arithmetic that reports its OWN CPU time, used as a
# proxy for the clock rate the daemons were running at. It has to report its own
# time: the shell's `times` builtin is useless here because reading it through a
# command substitution forks, and the fork's children-times start at zero.
calibrate() {
	awk -v n="${CALIB_ITERS:-20000000}" -v hz="$(getconf CLK_TCK)" 'BEGIN{
		x = 0
		for(i = 0; i < n; i++) x += i % 7
		if(x < 0) print x           # keep the loop from being optimised away
		getline line < "/proc/self/stat"
		split(line, f, " ")
		printf "%.3f\n", (f[14] + f[15]) / hz
	}'
}

pkts() { ip netns exec "$1" cat "/sys/class/net/$2/statistics/rx_packets" "/sys/class/net/$2/statistics/tx_packets" | awk '{n += $1} END {print n}'; }

# Let the link settle before the CPU counters are read: UDP discovery bursts and
# PMTU probing happen right after the tunnel comes up and are not steady-state
# forwarding cost. SETTLE=0 to measure from the first second instead.
sleep "${SETTLE:-5}"
ip netns exec b iperf3 -s -1 -D --logfile "$RUN/iperf-server.log"
sleep 2

case "${MODE:-udp}" in
	udp) IPERF_LOAD="-u -l ${DGRAM:-1300}" ;;
	tcp) IPERF_LOAD="" ;;
	*) echo "unknown MODE ${MODE:-}" >&2; exit 2 ;;
esac

cal0=$(calibrate)
a0=$(cpu_ticks a); b0=$(cpu_ticks b); pa0=$(pkts a "$TUN_A"); w0=$(date +%s.%N)
# shellcheck disable=SC2086  # IPERF_LOAD is a deliberate word-split option list
ip netns exec a iperf3 -c "$B_VPN" -b "$RATE" -t "$SECONDS_RUN" $IPERF_LOAD -J > "$RUN/iperf.json" 2>&1 || {
	log "iperf3 failed"; tail -5 "$RUN/iperf.json" >&2; exit 1; }
w1=$(date +%s.%N); a1=$(cpu_ticks a); b1=$(cpu_ticks b); pa1=$(pkts a "$TUN_A")
cal1=$(calibrate)
CAL=$(awk -v a="$cal0" -v b="$cal1" 'BEGIN{printf "%.3f\n", (a + b) / 2}')
log "calibration loop: ${cal0}s before, ${cal1}s after"

hz=$(getconf CLK_TCK)
bits=$(awk -F'[:,]' '/"bits_per_second"/{v=$2} END{print v+0}' "$RUN/iperf.json")
bytes=$(awk -F'[:,]' '/"bytes"/{v=$2} END{print v+0}' "$RUN/iperf.json")
retr=$(awk -F'[:,]' '/"retransmits"/{v=$2} END{print v+0}' "$RUN/iperf.json")

# One CSV line: arm, achieved Mbit/s, GB moved, tincd CPU seconds on each side,
# each as a percentage of one core, and peak RSS on each side.
awk -v arm="$ARM" -v hz="$hz" -v a0="$a0" -v a1="$a1" -v b0="$b0" -v b1="$b1" \
    -v w0="$w0" -v w1="$w1" -v bits="$bits" -v bytes="$bytes" -v retr="$retr" \
    -v ha="$(hwm_kb a)" -v hb="$(hwm_kb b)" -v pmtu="${pmtu:-0}" \
    -v pa0="$pa0" -v pa1="$pa1" -v mode="${MODE:-udp}" -v cal="$CAL" \
    -v carrier="$carrier" -v path="$path" 'BEGIN{
	wall = w1 - w0
	ca = (a1 - a0) / hz; cb = (b1 - b0) / hz
	gb = bytes / 1e9
	mp = (pa1 - pa0) / 1e6
	printf "%s,%s,%s,%s,%.1f,%.3f,%.3f,%.2f,%.2f,%.1f,%.1f,%.2f,%.2f,%d,%d,%d,%.1f,%.3f,%.2f,%.2f\n",
	       arm, carrier, path, mode, bits/1e6, gb, mp, ca, cb, 100*ca/wall, 100*cb/wall,
	       (mp>0 ? ca/mp : 0), (mp>0 ? cb/mp : 0), ha, hb, pmtu, wall,
	       cal, (cal>0 && mp>0 ? ca/cal/mp : 0), (cal>0 && mp>0 ? cb/cal/mp : 0)
}'
